### ISSUE TITLE
Parallel implementation

### ISSUE THREAD

**Issue by darismendi** [mcubeg/packmol#15]
Dear developers, 

I have seen that older versions of packmol had a parallel implementation, and now I'm wondering if the latest version have such capabilities?

If so, could you please indicate to me the changes in the Makefile?

Many thanks in advance

**Comment by leandromartinez98** [comment]
The parallel version was discontinued as it was implemented. It is still available in older versions of packmol, for instance this one:

http://leandro.iqm.unicamp.br/packmol/versionhistory/packmol-15.084.tar.gz

To compile it, do:

tar -xzvf packmol-15.084.tar.gz

cd packmol
make parallel

and run it with 

ppackmol 4 input.inp

where 4 is the number of processors used.

This version lacks many of the features of the newer versions, I must notice. 

We are willing to implement the parallelization again in the newer versions soon.

**Comment by georopon** [comment]
Novel version are disponible with parallel?

**Comment by lmiq** [comment]
No, not yet.
