### ISSUE TITLE
Regarding system setup in circular form from Packmol

### ISSUE THREAD

**Issue by cy16f01** [mcubeg/packmol#16]
I want to align say amino-acid in a circular (like micelle form in which the hydrophobic part in embedded inside and the hydrophilic around outside) fashion and then stack it in cylindrical form.
A rough image of the needed structure is shown:

![1](https://user-images.githubusercontent.com/30516979/58022082-3f28eb80-7b2a-11e9-9d67-981667d681ba.jpg)

Any suggestions on how can i make it..??

Any suggestions are appreciated.
Thank you.

**Comment by leandromartinez98** [comment]
This is not a software issue. Responded already by e-mail.
